### ISSUE TITLE
Prometheus erro

### ISSUE THREAD

**Issue by smallfish01** [rverchere/vmware_exporter#13]
Hi, When I compled the configuration and restart prometheus service, I got the error as below:
time="2017-08-09T17:34:37+08:00" level=info msg="Loading configuration file prometheus.yml" source="main.go:252" 
time="2017-08-09T17:34:37+08:00" level=error msg="Error reading file "/opt/vmware_exporter/config.yml": yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into []*config.TargetGroup" source="file.go:199" 
time="2017-08-09T17:34:38+08:00" level=error msg="Error reading file "/opt/vmware_exporter/config.yml": yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into []*config.TargetGroup" source="file.go:199"

My config.yml configuration is:
default:
    vmware_user: 'administrator@vsphere.local'
    vmware_password: 'Er4545'
    ignore_ssl: True

esx:
    vmware_user: 'root'
    vmware_password: 'Er4545'
    ignore_ssl: True

Do you know why?

Thank you!

**Comment by wtip** [comment]
What is the above log file output from? The prometheus server or the vmware_exporter?
If you are using 
```
default:
vmware_user: 'administrator@vsphere.local'
vmware_password: 'Er4545'
ignore_ssl: True

esx:
vmware_user: 'root'
vmware_password: 'Er4545'
ignore_ssl: True
```
as your prometheus server configuration it's not going to work. This would be the configuration for the vmware_exporter.

**Comment by smallfish01** [comment]
Hi Wtip,

Thanks for your replied. 
The log from Prometheus server, vmware_exporter is ok, I can saw the port has been opened.
# netstat -anp|grep 9272
tcp        0      0 0.0.0.0:9272            0.0.0.0:*               LISTEN      6268/python     


So did you means I should remove "- /opt/vmware_exporter/config.yml" from my Prometheus configation?

My Prometheus configuration as below:

# For Vmware ESXi
   - job_name: 'vmware_esx'
     metrics_path: '/metrics'
     file_sd_configs:
      - files:
        - /opt/vmware_exporter/config.yml
     params:
      section: [esx]
     relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.100.10:9272

**Comment by smallfish01** [comment]
When I access from web: http://192.168.100.22:9272/, I got the information:

No Such Resource
No such child resource.

**Comment by wtip** [comment]
@smallfish01 yes you are using the `file_sd_configs:` prometheus configuration incorrectly.
Have a look at https://prometheus.io/docs/operating/configuration/#<file_sd_config> and https://prometheus.io/blog/2015/06/01/advanced-service-discovery/#custom-service-discovery

however it might be easier for you to use the first configuration example that doesn't use the file based service discovery.
```
  - job_name: 'vmware_vcenter'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'vcenter.company.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9272
```

Also you can't just access `http://192.168.100.22:9272/`
You need to use some thing like `http://192.168.100.22:9272/metrics?target=vcenter.company.com` but change vcenter.company.com to the name of your vcenter or esxi server domain
